package model

// Fielder describes any type that can expose its schema and
// writable pointers. It is the shared contract between orm (database),
// form (UI), and json layers, replacing runtime reflection.
//
// Implementations are generated by code generators — never written by hand.
//
// Contract:
//   - Schema() and Pointers() MUST return slices of the same length.
//   - The i-th element in each slice corresponds to the same struct field.
//   - Pointers() returns pointers to fields for reading (dereference) and writing (scan/sync).
type Fielder interface {
	Schema() []Field
	Pointers() []any
}

// FielderSlice is implemented by generated code to allow
// iteration over a slice of structs without reflection.
type FielderSlice interface {
	Fielder
	Len() int
	At(i int) Fielder
	Append() Fielder
}

// Widget is the contract for a semantic input type.
// It is implemented by tinywasm/form/input types and custom project inputs.
// Stored in Field.Widget; set by ormc code generation from the `input:` struct tag.
//
// Implementations must be stateless templates — Clone() returns a fresh copy
// for thread-safe use per request in the form layer.
//
// RenderHTML is intentionally excluded: rendering is a concern of tinywasm/form,
// not of the base schema package.
type Widget interface {
	Type() string                       // Semantic input type (e.g., "email", "textarea")
	Validate(value string) error        // Semantic validation for this input type
	Clone(parentID, name string) Widget // Returns a positioned instance; pass ("","") for a bare template
}

// Validator is implemented by types that can self-validate.
// Generated by ormc: func (m *X) Validate(action byte) error { return model.ValidateFields(action, m) }
// Used by form, json.Decode, and orm pre-insert to enforce data integrity.
type Validator interface {
	Validate(action byte) error
}

// ModuleNaming is the minimal identity contract shared across the ecosystem: a
// stable model name used as route key, nav hash and DOM id. Consumers that need only
// identity (routing, layout shells) embed this; data models embed the richer Model.
type ModuleNaming interface {
	ModelName() string
}

// Model describes a resource with a schema and a name.
// Standard interface used by DB, Form, and API layers.
type Model interface {
	Fielder
	ModuleNaming
}

// SafeFields combines schema access with validation.
// Handlers that receive user input should accept SafeFields
// to enforce compile-time validation guarantees.
type SafeFields interface {
	Fielder
	Validator
}
